spring.application.name=demo

# Conexión a SQL Server en Docker
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TuBaseDeDatos;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=TuPassword123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
